plugins {
  id 'com.android.application'
}

android {
  namespace 'org.legendofdragoon.severedchains.android'
  compileSdk 35
  buildToolsVersion '35.0.0'

  defaultConfig {
    applicationId 'org.legendofdragoon.severedchains.android'
    minSdk 26
    targetSdk 35
    versionCode 6
    versionName '0.1.5'

    ndk {
      abiFilters 'arm64-v8a'
    }

    externalNativeBuild {
      cmake {
        cppFlags '-std=c17'
      }
    }
  }

  buildTypes {
    debug {
      applicationIdSuffix '.debug'
      versionNameSuffix '-debug'
    }
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  externalNativeBuild {
    cmake {
      path file('src/main/cpp/CMakeLists.txt')
      version '3.22.1'
    }
  }
}

android.applicationVariants.configureEach { variant ->
  variant.outputs.configureEach {
    outputFileName = "Severed-Chains-Android-${variant.versionName}.apk"
  }
}

def cxxRuntimeRoot = layout.buildDirectory.dir('generated/jniLibs')
def cxxRuntimeOutput = layout.buildDirectory.dir('generated/jniLibs/arm64-v8a')
tasks.register('copyCxxRuntime', Copy) {
  from file("${android.ndkDirectory}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so")
  into cxxRuntimeOutput
}
tasks.named('preBuild').configure {
  dependsOn tasks.named('copyCxxRuntime')
}

android.sourceSets.named('main') {
  jniLibs.srcDir(cxxRuntimeRoot)
}

dependencies {
  implementation 'org.apache.commons:commons-compress:1.28.0'
  implementation 'org.tukaani:xz:1.10'
}
